"""
Wallapop API status → internal unified status mapping.

The production system uses 9 internal states that normalize across all
marketplace platforms (Wallapop, eBay, etc.). Wallapop's API returns 18+
distinct status codes that map to these unified states.
"""

WALLAPOP_TO_INTERNAL = {
    "TRANSACTION_CREATED": "POR_ENVIAR",
    "REQUEST_CREATED": "POR_ENVIAR",
    "PENDING_TO_MEET": "POR_ENVIAR",
    "DEPOSITED_AT_PUDO": "ENVIADO",
    "AVAILABLE_FOR_THE_RECIPIENT_CARRIER_OFFICE": "ENVIADO",
    "TRANSACTION_DEFAULT": "ENVIADO",
    "DELIVERED_TO_CARRIER": "ENVIADO",
    "IN_TRANSIT": "ENVIADO",
    "AVAILABLE_FOR_THE_RECIPIENT_HOME_PICKUP": "ENVIADO",
    "ON_HOLD_AT_CARRIER": "ENVIADO",
    "ON_HOLD_INSTRUCTIONS_RECEIVED": "ENVIADO",
    "DELIVERED": "ENTREGADO",
    "DISPUTE_OPEN": "INCIDENCIA",
    "DISPUTE_ESCALATED": "INCIDENCIA",
    "RETURN_INCIDENT": "INCIDENCIA",
    "RETURN_IN_PROGRESS": "EN_DEVOLUCION",
    "DELIVERY_RETURNING_TO_SENDER": "EN_DEVOLUCION",
    "CANCELLED": "CANCELADO",
}

SHIPPED_STATES = {"ENVIADO", "ENTREGADO", "COMPLETADO"}
RETURN_STATES = {"EN_DEVOLUCION", "INCIDENCIA"}
ITEMS_LEFT_WAREHOUSE = {"ENVIADO", "ENTREGADO", "COMPLETADO", "EN_DEVOLUCION", "REEMBOLSADO"}
